# Site settings
title: faustocv
email: info@faustocv.org
description: >- # this means to ignore newlines until "baseurl:"
  I am a full stack developer. My focus areas are DevOps, software coding, architectural design, IoT / WoT, TDD and Continuous Delivery.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://faustocv.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _faustocv
github_username:  faustocv

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Makefile
