# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            faustocv
tagline:          'In two languages'
description:      'Full-stack development and DevOps stuff'
baseurl:          /
url: "http://www.faustocv.org"

# Analytics
google_analytics: UA-126666069-1
